CREATE
USER federation_mercurius_todo_item WITH SUPERUSER;
CREATE
DATABASE federation_mercurius_todo_item;
GRANT ALL PRIVILEGES ON DATABASE
federation_mercurius_todo_item TO federation_mercurius_todo_item;

CREATE
USER federation_mercurius_user WITH SUPERUSER;
CREATE
DATABASE federation_mercurius_user;
GRANT ALL PRIVILEGES ON DATABASE
federation_mercurius_user TO federation_mercurius_user;
